# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://prestonwu.com
title: Asian Boy from Utah
email: preston.wu1114@gmail.com
author: Preston Wu
description: > # "I am cuffed to a beautiful girl names M**** T**. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2019 Preston Wu. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/PrestonWu1114
  - title: instagram
    url: https://www.instagram.com/pressedonwu/
  - title: linkedin
    url: https://www.linkedin.com/in/preston-wu1114/

